<?php
/**
 * Copyright © 2015 v2modules commerce. All rights reserved.
 */
 ?>
 
 <script type="text/javascript">
	!function(){
		var t=window.divvit=window.divvit||[];
		if(t.DV_VERSION="prestashop-<?=$block->version?>",
			t.init=function(e){
				if(!t.bInitialized){
					var i=document.createElement("script");
					i.setAttribute(
						"type",
						"text/javascript"
					),
					i.setAttribute("async",!0),
					i.setAttribute("src","<?=$block->tag_url?>/tag.js?id="+e);
					var n=document.getElementsByTagName("script")[0];
					n.parentNode.insertBefore(i,n)
				}
			},
			!t.bInitialized
		){
			t.functions=["customer","pageview","cartAdd","cartRemove","cartUpdated","orderPlaced","nlSubscribed","dv"];
			for(var e=0;e<t.functions.length;e++){
				var i=t.functions[e];
				t[i]=function(e){
					return function(){
						return Array.prototype.unshift.call(arguments,e),t.push(arguments),t
					}
				}(i)
			}
		}
	}();

	divvit.init('<?=$block->merchant?>');
	divvit.pageview();
</script>
